# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  encoding: utf8
  database: toilet_development
  pool: 5
  username: root
  password: secret
  port: 13306
  host: 127.0.0.1
  timeout: 5000

test:
  adapter: mysql2
  encoding: utf8
  database: toilet_test
  pool: 5
  username: test
  password: test
  port: 13306
  host: 127.0.0.1
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  database: toilet_production
  pool: 5
  username: root
  password: secret
  port: 13306
  host: 127.0.0.1
  timeout: 5000
