# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development: &default
  adapter: mysql2
  encoding: utf8
  database: toilet_development
  pool: 5
  username: root
  password: secret
  port: 3306
  host: db
  timeout: 5000
